### ISSUE TITLE
ObjectStorage and projects

### ISSUE THREAD

**Issue by hlidotbe** [matthprost/Scaleway-Manager#13]
Hi,

When switching projects instances change as expected but I still see the default ObjectStorage. Tried with different projects and restarting the app to no avail. 

Tested on latest iOS beta, iPhone 12

**Comment by matthprost** [comment]
Hello,

Sorry for late answer, you are right token were scoped by default project and not automatically switched depending on it. 
I pushed a fix it should be soon published on Apple Store and Android Store.

Thank you for your report !
