### ISSUE TITLE
App crashes on using 'Mail'-Button

### ISSUE THREAD

**Issue by FrankyColonia** [matthprost/scaleway-manager#25]
Hey there,

actually using App v2.3.3 from the official Google PlayStore on a Samsung Note 10+ with Android v12 (with Google Play Update from Feb 2024) and Kernel v4.14.113-24230781 

When pushing the 'Mail'/Envelope-Button (behind the question mark) the app crashes completely immediately. 

Can someone fix this?

**Comment by VLNTNO** [comment]
Hello,
I have the same issue on a Pixel 8 with GrapheneOS installed.
Best regards.

**Comment by matthprost** [comment]
Hello,

Thank you for the feedback, I'm currently working on a new version #28 that should be released soon. The mail button should be removed as the SMTP server is down. In order to ask for help users will have to create an issue on github.

Have a nice day!

**Comment by matthprost** [comment]
The new release is available here: https://github.com/matthprost/scaleway-manager/releases/tag/2.4.1
And of course on Apple Store and Google Play Store.

Don't hesitate to reopen your issue if you think it hasn't been solved.
