### ISSUE TITLE
2FA Error on logging in - No Login possible 

### ISSUE THREAD

**Issue by FrankyColonia** [matthprost/scaleway-manager#26]
Hey there,

I'd like to use the app on my Samsung Note 10+ with Android v12 (Play Updates from Feb-2024)
But I can't login. 

After filling Username & PW and solving the reCAPTCHA I always get this message on the Top of the screen (on a red background):

Error: Two-factor authentication Error

The message will throw me back to the login prompt 😭

Any help appreciated. Just let me know if I can support with providing additional information.

Thank you, best
Frank

**Comment by Azraeht** [comment]
I'm facing the same issue and I can't log on the application. Any idea about how to troubleshoot or fix it?

**Comment by matthprost** [comment]
Hello!

Sorry for late answer, it seems like Scaleway changed their captcha from reCaptcha to friendlyCaptcha. I'm currently working on a update (#28) of the app to integrate this captcha and make it work like it did before.

Hopefully it should be available by next week.
Have a nice day!

**Comment by matthprost** [comment]
The new release is available here: https://github.com/matthprost/scaleway-manager/releases/tag/2.4.1
And of course on Apple Store and Google Play Store.

Don't hesitate to reopen your issue if you think it hasn't been solved.
