### ISSUE TITLE
Alternative Download

### ISSUE THREAD

**Issue by IzzySoft** [matthprost/Scaleway-Manager#8]
Would you consider making the APK available for the folks outside Play Store (Huawei devices, privacy folks) – eg by attaching it to the corresponding release, or even bringing it to [F-Droid](https://f-droid.org/)? Thanks in advance!

**Comment by matthprost** [comment]
Hello!
That's a good idea, I published `.apk` file for version 2.2.1: https://github.com/matthprost/Scaleway-Manager/releases/tag/2.2.1

**Comment by IzzySoft** [comment]
Thanks Matthias! I took the freedom of adding it to my repo (should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.matthiasprost.scalewaymanager) with the next sync in about 23h). Expect a PR from me soon to get you started with Fastlane (makes it easier to maintain app description, screenshots etc. in one place, deploying them to many: it's eg supported by F-Droid, by my repo, Google Play and the apple store).

Another question: unfortunately, your app uses some proprietary trackers. According to my library scanner eg Firebase Analytics, which probably is the only one you've explicitly "invited", and then GMS, Firebase (most likely FCM) and Firebase transport. Would you think it possible having a "real FOSS" build flavor skipping those – and providing the resulting APK? Just a friendly question, so you of course can say "No" (though I'm of course hoping for a "Yes" :wink:) It's not just a philosophical question (FOSS vs proprietary) – but also a privacy one… Thanks!
